AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  Send RDS logs to S3
Resources:
  RDSLogsToS3:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      Timeout: 60
      Handler: main.lambda_handler
      Environment:
        Variables:
          RDS_INSTANCE_NAME: blue-transition-postgresql-standby
          S3_BUCKET_NAME: govuk-integration-aws-logging
          S3_BUCKET_PREFIX: rds/blue-transition-postgresql-standby/
          LAST_RECEIVED_FILE: last_received.log
          LOG_NAME_PREFIX: error/
