name: govuk-aws-linting
on: [push, pull_request]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: bundle
      - run: bundle install --deployment

      - name: Docs Check
        run: |
          brew install terraform-docs
          echo "Checking the updatedness of README files..."
          ./tools/update-docs.sh

          if ! git diff --exit-code; then
            echo "The documentation isn't up to date. You should run ./tools/update-docs.sh and commit the results."
            exit 1
          fi

      - name: Shellcheck
        run: |
          brew install shellcheck

          echo "Running shellcheck..."
          shellcheck -e SC2086,SC1117 jenkins.sh tools/*.sh terraform/userdata/*

      - name: terraform fmt
        run: |
          brew install tfenv
          tfenv install
          find . -name '*.tf' | xargs tools/terraform-format.sh

      - name: RSpec
        run: bundle exec rspec spec/validate_resources_spec.rb   

      - name: Lint Resource Names
        run: bundle exec lib/resource_name_lint.rb

      - name: JSON Check
        run: find . -name '*.json' | xargs tools/json-check.sh

      - name: ADR Check
        run: tools/adr-check.sh
